using System.ComponentModel.DataAnnotations;

namespace CRAS.Domain.Entities;

/// <summary>
///     Representation of a financial statement.
/// </summary>
public class FinancialStatement
{
    /// <summary>
    ///     Gets or sets the identifier of the contractor associated with the financial statement.
    /// </summary>
    [Required]
    public Guid ContractorId { get; set; }

    /// <summary>
    ///     Gets the unique identifier for the financial statement.
    /// </summary>
    public Guid Id { get; private set; } = Guid.NewGuid();

    /// <summary>
    ///     Gets the fiscal year associated with the financial statement.
    /// </summary>
    public int Year { get; init; }

    /// <summary>
    ///     Gets the total value of all assets owned by the contractor.
    /// </summary>
    public decimal TotalAssets { get; init; }

    /// <summary>
    ///     Gets the total value of all liabilities or debts owed by the contractor.
    /// </summary>
    public decimal TotalLiabilities { get; init; }

    /// <summary>
    ///     Gets the value of current assets, which are expected to be converted to cash within one year.
    /// </summary>
    public decimal CurrentAssets { get; init; }

    /// <summary>
    ///     Gets the value of current liabilities, which are due to be paid within one year.
    /// </summary>
    public decimal CurrentLiabilities { get; init; }

    /// <summary>
    ///     Gets the working capital, representing the difference between current assets and current liabilities.
    /// </summary>
    public decimal WorkingCapital { get; init; }

    /// <summary>
    ///     Gets the cumulative number of retained earnings over the life of the contractor.
    /// </summary>
    public decimal RetainedEarnings { get; init; }

    /// <summary>
    ///     Gets the Earnings Before Interest and Taxes (EBIT), reflecting operational profitability.
    /// </summary>
    public decimal EBIT { get; init; }

    /// <summary>
    ///     Gets the market value of equity, representing the total value of the contractor's outstanding shares.
    /// </summary>
    public decimal MarketValueEquity { get; init; }

    /// <summary>
    ///     Gets the book value of equity, representing the difference between total assets and total liabilities.
    /// </summary>
    public decimal BookValueEquity { get; init; }

    /// <summary>
    ///     Gets the total sales or revenue generated by the contractor during the fiscal year.
    /// </summary>
    public decimal Sales { get; init; }

    /// <summary>
    ///     Gets the net income (profit or loss) for the current fiscal year.
    /// </summary>
    public decimal NetIncome { get; init; }

    /// <summary>
    ///     Gets the net income for the previous fiscal year, required by specific risk models (e.g., Ohlson O-Score).
    /// </summary>
    public decimal PreviousNetIncome { get; init; }

    /// <summary>
    ///     Gets the funds generated from standard operations, excluding capital expenditures and investments.
    /// </summary>
    public decimal FundsFromOperations { get; init; }

    /// <summary>
    ///     Gets the Gross National Product (GNP) price index level applicable for the given fiscal year.
    /// </summary>
    public decimal GNPPriceIndex { get; init; }
}
