using System.Text.Json.Serialization;

namespace CRAS.Domain.Entities;

/// <summary>
///     Representation of a financial statement.
/// </summary>
public class FinancialStatement
{
    /// <summary>
    ///     Gets the unique identifier for the financial statement.
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>
    ///     Gets or sets the identifier of the contractor associated with the financial statement.
    /// </summary>
    public required Guid ContractorId { get; set; }

    /// <summary>
    ///     Gets the fiscal year associated with the financial statement.
    /// </summary>
    public required int Year { get; init; }

    /// <summary>
    ///     Gets the total value of all assets owned by the contractor.
    /// </summary>
    public required decimal TotalAssets { get; init; }

    /// <summary>
    ///     Gets the total value of all liabilities or debts owed by the contractor.
    /// </summary>
    public required decimal TotalLiabilities { get; init; }

    /// <summary>
    ///     Gets the value of current assets, which are expected to be converted to cash within one year.
    /// </summary>
    public required decimal CurrentAssets { get; init; }

    /// <summary>
    ///     Gets the value of current liabilities, which are due to be paid within one year.
    /// </summary>
    public required decimal CurrentLiabilities { get; init; }

    /// <summary>
    ///     Gets the working capital, representing the difference between current assets and current liabilities.
    /// </summary>
    public required decimal WorkingCapital { get; init; }

    /// <summary>
    ///     Gets the cumulative number of retained earnings over the life of the contractor.
    /// </summary>
    public required decimal RetainedEarnings { get; init; }

    /// <summary>
    ///     Gets the Earnings Before Interest and Taxes (EBIT), reflecting operational profitability.
    /// </summary>
    // ReSharper disable once InconsistentNaming
    public required decimal EBIT { get; init; }

    /// <summary>
    ///     Gets the market value of equity, representing the total value of the contractor's outstanding shares.
    /// </summary>
    public required decimal MarketValueEquity { get; init; }

    /// <summary>
    ///     Gets the book value of equity, representing the difference between total assets and total liabilities.
    /// </summary>
    public required decimal BookValueEquity { get; init; }

    /// <summary>
    ///     Gets the total sales or revenue generated by the contractor during the fiscal year.
    /// </summary>
    public required decimal Sales { get; init; }

    /// <summary>
    ///     Gets the net income (profit or loss) for the current fiscal year.
    /// </summary>
    public required decimal NetIncome { get; init; }

    /// <summary>
    ///     Gets the net income for the previous fiscal year, required by specific risk models.
    /// </summary>
    public required decimal PreviousNetIncome { get; init; }

    /// <summary>
    ///     Gets the funds generated from standard operations, excluding capital expenditures and investments.
    /// </summary>
    public required decimal FundsFromOperations { get; init; }

    /// <summary>
    ///     Gets the Gross National Product (GNP) price index level applicable for the given fiscal year.
    /// </summary>
    // ReSharper disable once InconsistentNaming
    public required decimal GNPPriceIndex { get; init; }

    /// <summary>
    ///     Gets the navigation property to the associated contractor.
    /// </summary>
    [JsonIgnore]
    public Contractor Contractor { get; set; } = null!;
}
