@HostAddress = http://localhost:5250

GET {{HostAddress}}/api/contractors
Accept: application/json

###

GET {{HostAddress}}/api/contractors/09e5bc0f-0ab5-42c1-9ac7-086a81ddf40a/assess
Accept: application/json

###
